AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handler
      Runtime: nodejs8.10
      CodeUri: ./application/
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
  MetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: metadata.handler
      Runtime: nodejs8.10
      CodeUri: ./metadata/
      Role: arn:aws:iam::723736099413:role/lambda_codebuild
      Events:
        MetadataApi:
          Type: Api
          Properties:
            Path: /metadata
            Method: GET