AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World
Resources:
  Config:
    Type: "Custom:Config"
    Version: "1.0"
    Properties:
      Stage: Prod
      TableName: ApplicationCalls
      APIHostName: "vcwgpbc01m.execute-api.ap-southeast-2.amazonaws.com"
  LambdaCodePilelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodePipelineReadOnlyAccess"
      MaxSessionDuration: 3600
      Path: /
      RoleName: "myob_lambda_codepipeline"
  LambdaDynamoDBRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        MaxSessionDuration: 3600
        Path: /
        RoleName: "myob_lambda_dynamodb"
  LambdaHealthRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: "sts:AssumeRole"
          ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess"
          MaxSessionDuration: 3600
          Path: /
          RoleName: "myob_lambda_health"
  ApplicationCallsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !GetAtt [ Config, TableName ]
        AttributeDefinitions:
          - AttributeName: ApplicationName
            AttributeType: S
        KeySchema:
          - AttributeName: ApplicationName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handler
      Runtime: nodejs8.10
      CodeUri: ./application/
      Environment:
        Variables:
          TableName: !GetAtt [ Config, TableName ]
          ApplicationName: myobTechnicalTest
      Role: !GetAtt [ LambdaDynamoDBRole, Arn ]
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
  MetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: metadata.handler
      Runtime: nodejs8.10
      CodeUri: ./metadata/
      Environment:
        Variables:
          PipelineName: "myob-pipeline"
      Role: !GetAtt [ LambdaCodePilelineRole, Arn ]
      Events:
        MetadataApi:
          Type: Api
          Properties:
            Path: /metadata
            Method: GET
  HealthFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: health.handler
        Runtime: nodejs8.10
        CodeUri: ./health/
        Environment:
          Variables:
            TableName: !GetAtt [ Config, TableName ]
            HostName: !GetAtt [ Config, APIHostName ]
            Stage: !GetAtt [ Config, Stage ]
        Role: !GetAtt [ LambdaHealthRole, Arn ]
        Events:
          HealthApi:
            Type: Api
            Properties:
              Path: /health
              Method: GET