AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World
Resources:
  LambdaCodePilelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: Json
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/AWSCodePipelineReadOnlyAccess"]
      MaxSessionDuration: 3600
      Path: /
      RoleName: "myob_lambda_codepipeline"
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handler
      Runtime: nodejs8.10
      CodeUri: ./application/
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
  MetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: metadata.handler
      Runtime: nodejs8.10
      CodeUri: ./metadata/
      Role: !Ref LambdaCodePilelineRole
      Events:
        MetadataApi:
          Type: Api
          Properties:
            Path: /metadata
            Method: GET