AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World
Parameters:
  Stage:
    Type: String
    Default: Prod
  APIHostName:
    Type: String
    Default: "vcwgpbc01m.execute-api.ap-southeast-2.amazonaws.com"
Resources:
  LambdaCodePilelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodePipelineReadOnlyAccess"
      MaxSessionDuration: 3600
      Path: /
      RoleName: "myob_lambda_codepipeline"
  LambdaDynamoDBRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        MaxSessionDuration: 3600
        Path: /
        RoleName: "myob_lambda_dynamodb"
  LambdaHealthRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: "sts:AssumeRole"
          ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess"
          MaxSessionDuration: 3600
          Path: /
          RoleName: "myob_lambda_health"
  ApplicationCallsDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ApplicationName
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handler
      Runtime: nodejs8.10
      CodeUri: ./application/
      Environment:
        Variables:
          TableName: !Ref ApplicationCallsDynamoDBTable
          ApplicationName: myobTechnicalTest
      Role: !GetAtt [ LambdaDynamoDBRole, Arn ]
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
  MetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: metadata.handler
      Runtime: nodejs8.10
      CodeUri: ./metadata/
      Environment:
        Variables:
          PipelineName: "myob-pipeline"
      Role: !GetAtt [ LambdaCodePilelineRole, Arn ]
      Events:
        MetadataApi:
          Type: Api
          Properties:
            Path: /metadata
            Method: GET
  HealthFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: health.handler
        Runtime: nodejs8.10
        CodeUri: ./health/
        Environment:
          Variables:
            TableName: !Ref ApplicationCallsDynamoDBTable
            HostName:
              Fn::Join:
                - ""
                - - "https://"
                  - Ref: HelloWorldApi
                  - ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}"
            Stage: !Ref Stage
        Role: !GetAtt [ LambdaHealthRole, Arn ]
        Events:
          HealthApi:
            Type: Api
            Properties:
              Path: /health
              Method: GET